
files:
  branchUrl:  https://raw.githubusercontent.com/EricomSoftwareLtd/Shield/consep/Setup/
  yaml: docker-compose_dev.yml

credentials:
  git: 451bb7d7-5c99-4d21-aa3a-1c6a1027406b
  docker: beny-docker


svc:
  url: 'https://github.com/EricomSoftwareLtd/SB.git'
  branch: consul

notification:
  mails:
    - shield.build@ericom.com
    - lev.ozeryansky@ericom.com